import {
	Captions,
	CaptionsOff,
	Download,
	Globe,
	Minus,
	Palette,
	Plus,
	RefreshCw,
	Settings2,
	Sparkles,
	X,
} from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { addToHistory } from "../services/api";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface SubtitleTrack {
	language: string;
	languageCode: string;
	label: string;
	url: string;
	format: "vtt" | "srt" | "json";
	isAutoGenerated?: boolean;
	isCommunity?: boolean;
}

export interface SubtitleStyle {
	fontSize: number; // in pixels or percentage
	fontColor: string;
	backgroundColor: string;
	backgroundOpacity: number;
	fontFamily: string;
	textShadow: boolean;
}

export interface SubtitleCue {
	start: number; // seconds
	end: number; // seconds
	text: string;
}

interface SubtitleManagerProps {
	videoKey: string;
	subtitleUrl?: string;
	onStyleChange?: (style: SubtitleStyle) => void;
	onTrackChange?: (track: SubtitleTrack | null) => void;
}

// ─── Default Styles ─────────────────────────────────────────────────────────

const DEFAULT_STYLE: SubtitleStyle = {
	fontSize: 16,
	fontColor: "#FFFFFF",
	backgroundColor: "#000000",
	backgroundOpacity: 0.75,
	fontFamily: "Arial, sans-serif",
	textShadow: true,
};

const FONT_SIZES = [12, 14, 16, 18, 20, 24, 28, 32];
const FONT_COLORS = [
	"#FFFFFF",
	"#FFFF00",
	"#00FFFF",
	"#00FF00",
	"#FF00FF",
	"#FFA500",
];
const BG_COLORS = ["#000000", "#1A1A1A", "#2D2D2D", "#FFFFFF", "transparent"];

// ─── Utility Functions ──────────────────────────────────────────────────────

const parseVTT = (content: string): SubtitleCue[] => {
	const cues: SubtitleCue[] = [];
	const lines = content.split(/\r?\n/);
	let i = 0;

	while (i < lines.length) {
		const line = lines[i].trim();

		// Skip WEBVTT header and empty lines
		if (line.startsWith("WEBVTT") || line === "" || line.match(/^\d+$/)) {
			i++;
			continue;
		}

		// Parse timestamp line (e.g., "00:00:01.000 --> 00:00:04.000")
		const timestampMatch = line.match(
			/(\d{2}:\d{2}:\d{2}\.\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}\.\d{3})/,
		);
		if (timestampMatch) {
			const start = parseTimestamp(timestampMatch[1]);
			const end = parseTimestamp(timestampMatch[2]);

			// Collect text lines until empty line
			i++;
			const textLines: string[] = [];
			while (i < lines.length && lines[i].trim() !== "") {
				textLines.push(lines[i].trim());
				i++;
			}

			if (textLines.length > 0) {
				cues.push({
					start,
					end,
					text: textLines.join("\n"),
				});
			}
		}
		i++;
	}

	return cues;
};

const parseTimestamp = (ts: string): number => {
	const [time, ms] = ts.split(".");
	const [h, m, s] = time.split(":").map(Number);
	return h * 3600 + m * 60 + s + (ms ? parseInt(ms, 10) / 1000 : 0);
};

const parseSRT = (content: string): SubtitleCue[] => {
	const cues: SubtitleCue[] = [];
	const blocks = content.split(/\r?\n\r?\n/);

	for (const block of blocks) {
		const lines = block.split(/\r?\n/);
		if (lines.length < 3) continue;

		// Skip index line
		const timestampLine = lines[1];
		const timestampMatch = timestampLine.match(
			/(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})/,
		);

		if (timestampMatch) {
			const start = parseSRTTimestamp(timestampMatch[1]);
			const end = parseSRTTimestamp(timestampMatch[2]);
			const text = lines.slice(2).join("\n");

			cues.push({ start, end, text });
		}
	}

	return cues;
};

const parseSRTTimestamp = (ts: string): number => {
	const [time, ms] = ts.split(",");
	const [h, m, s] = time.split(":").map(Number);
	return h * 3600 + m * 60 + s + (ms ? parseInt(ms, 10) / 1000 : 0);
};

const formatVTT = (cues: SubtitleCue[]): string => {
	let output = "WEBVTT\n\n";
	for (const cue of cues) {
		output += `${formatVTTTimestamp(cue.start)} --> ${formatVTTTimestamp(cue.end)}\n`;
		output += `${cue.text}\n\n`;
	}
	return output;
};

const formatVTTTimestamp = (seconds: number): string => {
	const h = Math.floor(seconds / 3600);
	const m = Math.floor((seconds % 3600) / 60);
	const s = Math.floor(seconds % 60);
	const ms = Math.floor((seconds % 1) * 1000);
	return `${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}.${ms.toString().padStart(3, "0")}`;
};

// ─── Component ──────────────────────────────────────────────────────────────

export function SubtitleManager({
	videoKey,
	subtitleUrl,
	onStyleChange,
	onTrackChange,
}: SubtitleManagerProps) {
	const [isOpen, setIsOpen] = useState(false);
	const [isEnabled, setIsEnabled] = useState(true);
	const [tracks, setTracks] = useState<SubtitleTrack[]>([]);
	const [activeTrack, setActiveTrack] = useState<SubtitleTrack | null>(null);
	const [cues, setCues] = useState<SubtitleCue[]>([]);
	const [currentTime, setCurrentTime] = useState(0);
	const [isLoading, setIsLoading] = useState(false);
	const [error, setError] = useState<string | null>(null);

	// Style state
	const [style, setStyle] = useState<SubtitleStyle>(DEFAULT_STYLE);
	const [showStylePanel, setShowStylePanel] = useState(false);

	// Sync offset in seconds
	const [syncOffset, setSyncOffset] = useState(0);

	// Auto-generate state
	const [isAutoGenerating, setIsAutoGenerating] = useState(false);

	const containerRef = useRef<HTMLDivElement>(null);
	const videoElement = useRef<HTMLVideoElement | null>(null);

	// Find video element
	useEffect(() => {
		const video = document.querySelector("video");
		if (video) {
			videoElement.current = video;

			const handleTimeUpdate = () => {
				setCurrentTime(video.currentTime);
			};

			video.addEventListener("timeupdate", handleTimeUpdate);
			return () => video.removeEventListener("timeupdate", handleTimeUpdate);
		}
	}, []);

	// Load available subtitle tracks
	useEffect(() => {
		const loadTracks = async () => {
			if (!subtitleUrl) return;

			setIsLoading(true);
			setError(null);

			try {
				// Default track from video
				const defaultTrack: SubtitleTrack = {
					language: "English",
					languageCode: "en",
					label: "English (Default)",
					url: subtitleUrl,
					format: "vtt",
				};

				// Fetch additional tracks from JW API or community sources
				const additionalTracks = await fetchSubtitleTracks(videoKey);

				setTracks([defaultTrack, ...additionalTracks]);
				setActiveTrack(defaultTrack);
				onTrackChange?.(defaultTrack);
			} catch (err) {
				setError("Failed to load subtitle tracks");
				console.error(err);
			} finally {
				setIsLoading(false);
			}
		};

		loadTracks();
	}, [subtitleUrl, videoKey, onTrackChange, fetchSubtitleTracks]);

	// Load subtitle content when track changes
	useEffect(() => {
		const loadSubtitles = async () => {
			if (!activeTrack || !isEnabled) {
				setCues([]);
				return;
			}

			setIsLoading(true);
			setError(null);

			try {
				const response = await fetch(activeTrack.url);
				const content = await response.text();

				let parsedCues: SubtitleCue[];

				if (activeTrack.format === "srt") {
					parsedCues = parseSRT(content);
				} else {
					parsedCues = parseVTT(content);
				}

				setCues(parsedCues);
			} catch (err) {
				setError("Failed to load subtitles");
				console.error(err);
			} finally {
				setIsLoading(false);
			}
		};

		loadSubtitles();
	}, [activeTrack, isEnabled]);

	// Notify parent of style changes
	useEffect(() => {
		onStyleChange?.(style);
	}, [style, onStyleChange]);

	// Notify parent of track changes
	useEffect(() => {
		onTrackChange?.(activeTrack);
	}, [activeTrack, onTrackChange]);

	// Fetch subtitle tracks from JW API or community sources
	const fetchSubtitleTracks = async (key: string): Promise<SubtitleTrack[]> => {
		try {
			// Try JW API first
			const response = await fetch(
				`https://api.jw.org/videos/${key}/subtitles`,
			);
			if (response.ok) {
				const data = await response.json();
				return data.tracks || [];
			}
		} catch {
			// Fall back to community sources
		}

		// Community-sourced subtitles (example implementation)
		return [
			{
				language: "Spanish",
				languageCode: "es",
				label: "Español",
				url: `/subtitles/${key}/es.vtt`,
				format: "vtt",
				isCommunity: true,
			},
			{
				language: "French",
				languageCode: "fr",
				label: "Français",
				url: `/subtitles/${key}/fr.vtt`,
				format: "vtt",
				isCommunity: true,
			},
		];
	};

	// Auto-generate captions using speech recognition
	const handleAutoGenerate = useCallback(async () => {
		if (!videoElement.current) return;

		setIsAutoGenerating(true);
		setError(null);

		try {
			// Check for Web Speech API support
			// @ts-expect-error - SpeechRecognition is not in standard types
			const SpeechRecognition =
				// @ts-expect-error
				window.SpeechRecognition || window.webkitSpeechRecognition;

			if (SpeechRecognition) {
				const recognition = new SpeechRecognition();

				recognition.continuous = true;
				recognition.interimResults = true;
				recognition.lang = "en-US";

				const generatedCues: SubtitleCue[] = [];
				let startTime = 0;

				recognition.onresult = (event: any) => {
					for (let i = 0; i < event.results.length; i++) {
						const result = event.results[i];
						const text = result[0].transcript;

						if (result.isFinal) {
							generatedCues.push({
								start: startTime,
								end: videoElement.current?.currentTime,
								text,
							});
							startTime = videoElement.current?.currentTime;
						}
					}
				};

				recognition.start();

				// Stop after video ends or after 5 minutes
				setTimeout(() => recognition.stop(), 300000);

				// Store generated captions
				setTimeout(() => {
					setCues(generatedCues);
					setActiveTrack({
						language: "English",
						languageCode: "en",
						label: "Auto-Generated",
						url: "",
						format: "vtt",
						isAutoGenerated: true,
					});
					setIsAutoGenerating(false);
				}, 5000);
			} else {
				throw new Error("Speech recognition not supported");
			}
		} catch (err) {
			setError("Auto-generation not supported in this browser");
			console.error(err);
			setIsAutoGenerating(false);
		}
	}, []);

	// Download subtitles
	const handleDownload = useCallback(() => {
		if (cues.length === 0 || !activeTrack) return;

		// Apply sync offset
		const adjustedCues = cues.map((cue) => ({
			...cue,
			start: cue.start + syncOffset,
			end: cue.end + syncOffset,
		}));

		const content = formatVTT(adjustedCues);
		const blob = new Blob([content], { type: "text/vtt" });
		const url = URL.createObjectURL(blob);

		const a = document.createElement("a");
		a.href = url;
		a.download = `${videoKey}_${activeTrack.languageCode}.vtt`;
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);

		// Track download in history
		addToHistory(videoKey);
	}, [cues, activeTrack, syncOffset, videoKey]);

	// Get current active cue
	const getCurrentCue = useCallback(() => {
		if (!isEnabled || cues.length === 0) return null;

		const adjustedTime = currentTime - syncOffset;
		return cues.find(
			(cue) => adjustedTime >= cue.start && adjustedTime <= cue.end,
		);
	}, [currentTime, cues, isEnabled, syncOffset]);

	// Style handlers
	const updateStyle = useCallback(
		<K extends keyof SubtitleStyle>(key: K, value: SubtitleStyle[K]) => {
			setStyle((prev) => ({ ...prev, [key]: value }));
		},
		[],
	);

	const currentCue = getCurrentCue();

	return (
		<>
			{/* Subtitle Toggle Button */}
			<button
				type="button"
				onClick={() => setIsOpen(true)}
				className="control-btn subtitle-btn"
				aria-label="Subtitles"
				aria-expanded={isOpen}
			>
				{isEnabled && activeTrack ? (
					<Captions size={20} className="active" />
				) : (
					<CaptionsOff size={20} />
				)}
			</button>

			{/* Subtitle Overlay */}
			{isEnabled && currentCue && (
				<div
					className="subtitle-overlay"
					style={{
						fontSize: `${style.fontSize}px`,
						color: style.fontColor,
						fontFamily: style.fontFamily,
						textShadow: style.textShadow
							? "2px 2px 4px rgba(0,0,0,0.8)"
							: "none",
					}}
				>
					<div
						className="subtitle-text"
						style={{
							backgroundColor:
								style.backgroundColor !== "transparent"
									? `${style.backgroundColor}${Math.round(
											style.backgroundOpacity * 255,
										)
											.toString(16)
											.padStart(2, "0")}`
									: "transparent",
						}}
					>
						{currentCue.text}
					</div>
				</div>
			)}

			{/* Subtitle Manager Panel */}
			{isOpen && (
				<div ref={containerRef} className="subtitle-manager-panel">
					<div className="panel-header">
						<h3>Subtitles</h3>
						<button
							type="button"
							onClick={() => setIsOpen(false)}
							className="close-btn"
							aria-label="Close"
						>
							<X size={20} />
						</button>
					</div>

					<div className="panel-content">
						{/* Enable/Disable Toggle */}
						<div className="subtitle-section">
							<button
								type="button"
								onClick={() => setIsEnabled(!isEnabled)}
								className={`toggle-btn ${isEnabled ? "active" : ""}`}
							>
								{isEnabled ? <Captions size={18} /> : <CaptionsOff size={18} />}
								<span>{isEnabled ? "Subtitles On" : "Subtitles Off"}</span>
							</button>
						</div>

						{isEnabled && (
							<>
								{/* Language Selection */}
								<div className="subtitle-section">
									<div className="section-header">
										<Globe size={16} />
										<span>Language</span>
									</div>
									{isLoading ? (
										<div className="loading">Loading tracks...</div>
									) : error ? (
										<div className="error">{error}</div>
									) : (
										<div className="track-list">
											{tracks.map((track) => (
												<button
													key={track.languageCode}
													type="button"
													onClick={() => setActiveTrack(track)}
													className={`track-item ${activeTrack?.languageCode === track.languageCode ? "active" : ""}`}
												>
													<span>{track.label}</span>
													{track.isAutoGenerated && (
														<Sparkles size={12} className="auto-badge" />
													)}
													{track.isCommunity && (
														<span className="community-badge">Community</span>
													)}
												</button>
											))}
										</div>
									)}
								</div>

								{/* Sync Adjustment */}
								<div className="subtitle-section">
									<div className="section-header">
										<RefreshCw size={16} />
										<span>Sync Adjustment</span>
									</div>
									<div className="sync-controls">
										<button
											type="button"
											onClick={() => setSyncOffset((s) => s - 0.5)}
											className="sync-btn"
											aria-label="Decrease sync"
										>
											<Minus size={16} />
											<span>-0.5s</span>
										</button>
										<div className="sync-value">
											{syncOffset > 0 ? "+" : ""}
											{syncOffset.toFixed(1)}s
										</div>
										<button
											type="button"
											onClick={() => setSyncOffset((s) => s + 0.5)}
											className="sync-btn"
											aria-label="Increase sync"
										>
											<Plus size={16} />
											<span>+0.5s</span>
										</button>
										<button
											type="button"
											onClick={() => setSyncOffset(0)}
											className="sync-reset"
											aria-label="Reset sync"
										>
											Reset
										</button>
									</div>
								</div>

								{/* Style Customization */}
								<div className="subtitle-section">
									<div className="section-header">
										<Palette size={16} />
										<span>Style</span>
									</div>
									<button
										type="button"
										onClick={() => setShowStylePanel(!showStylePanel)}
										className="style-toggle"
									>
										<Settings2 size={16} />
										<span>Customize</span>
									</button>

									{showStylePanel && (
										<div className="style-panel">
											{/* Font Size */}
											<div className="style-option">
												<label>Size</label>
												<div className="size-options">
													{FONT_SIZES.map((size) => (
														<button
															key={size}
															type="button"
															onClick={() => updateStyle("fontSize", size)}
															className={`size-btn ${style.fontSize === size ? "active" : ""}`}
														>
															{size}
														</button>
													))}
												</div>
											</div>

											{/* Font Color */}
											<div className="style-option">
												<label>Text Color</label>
												<div className="color-options">
													{FONT_COLORS.map((color) => (
														<button
															key={color}
															type="button"
															onClick={() => updateStyle("fontColor", color)}
															className="color-btn"
															style={{
																backgroundColor: color,
																border:
																	style.fontColor === color
																		? "2px solid #fff"
																		: "2px solid transparent",
															}}
															aria-label={`Color ${color}`}
														/>
													))}
												</div>
											</div>

											{/* Background Color */}
											<div className="style-option">
												<label>Background</label>
												<div className="color-options">
													{BG_COLORS.map((color) => (
														<button
															key={color}
															type="button"
															onClick={() =>
																updateStyle("backgroundColor", color)
															}
															className="color-btn"
															style={{
																backgroundColor:
																	color === "transparent"
																		? "repeating-linear-gradient(45deg, #ccc 0, #ccc 1px, transparent 0, transparent 50%)"
																		: color,
																border:
																	style.backgroundColor === color
																		? "2px solid #fff"
																		: "2px solid transparent",
															}}
															aria-label={`Background ${color}`}
														/>
													))}
												</div>
											</div>

											{/* Background Opacity */}
											<div className="style-option">
												<label>
													Opacity: {Math.round(style.backgroundOpacity * 100)}%
												</label>
												<input
													type="range"
													min="0"
													max="1"
													step="0.05"
													value={style.backgroundOpacity}
													onChange={(e) =>
														updateStyle(
															"backgroundOpacity",
															Number(e.target.value),
														)
													}
													className="opacity-slider"
												/>
											</div>

											{/* Text Shadow */}
											<div className="style-option">
												<label className="checkbox-label">
													<input
														type="checkbox"
														checked={style.textShadow}
														onChange={(e) =>
															updateStyle("textShadow", e.target.checked)
														}
													/>
													Text Shadow
												</label>
											</div>
										</div>
									)}
								</div>

								{/* Auto-Generate */}
								<div className="subtitle-section">
									<button
										type="button"
										onClick={handleAutoGenerate}
										disabled={isAutoGenerating}
										className="auto-generate-btn"
									>
										<Sparkles size={16} />
										<span>
											{isAutoGenerating
												? "Generating..."
												: "Auto-Generate Captions"}
										</span>
									</button>
								</div>

								{/* Download */}
								<div className="subtitle-section">
									<button
										type="button"
										onClick={handleDownload}
										disabled={cues.length === 0}
										className="download-btn"
									>
										<Download size={16} />
										<span>Download Subtitles</span>
									</button>
								</div>
							</>
						)}
					</div>
				</div>
			)}
		</>
	);
}
